// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7YbPdzhG6gN33Mez_ApWk6FElmSVqo7Y',
    appId: '1:1042160734236:web:19df1ce45dba2a5cb58fd9',
    messagingSenderId: '1042160734236',
    projectId: 'appfhit',
    authDomain: 'appfhit.firebaseapp.com',
    storageBucket: 'appfhit.firebasestorage.app',
    measurementId: 'G-F05RNBNFY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnZba0rLX1n1X_5XsuUmCFJhUh9MCqhlc',
    appId: '1:1042160734236:android:e371b0fdcd7f29b3b58fd9',
    messagingSenderId: '1042160734236',
    projectId: 'appfhit',
    storageBucket: 'appfhit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUXpdjmEzitGvI5ZdszalBiLvwOcWI51U',
    appId: '1:1042160734236:ios:b89549c389d6e13fb58fd9',
    messagingSenderId: '1042160734236',
    projectId: 'appfhit',
    storageBucket: 'appfhit.firebasestorage.app',
    iosBundleId: 'com.example.flutterIfit',
  );
}
